Fix/introduce average newness for ypp
Joystream/orion pull request #137
Opened 2023-05-26 08:27 UTC by WRadoslaw

https://github.com/joystream/atlas/issues/4224

2023-05-26 13:21 UTC, Lezek123 requested changes

2023-05-26 14:43 UTC, Lezek123 commented on src/mappings/content/video.ts
> +    const ytPublishDate = new Date(video.publishedBeforeJoystream)
Good point, so we would either need to disable changing `publishedBeforeJoystream` for YPP videos or store this information in some other, immutable field (similar to `ytVideoId`)

2023-05-29 08:29 UTC, dmtrjsg commented
Thanks for bringing these comments up, but guys let's not worry about the hypothetical problem before this happens. So I suggest for us to just go ahead and merge it and if we see someone is taking advantage of this, we can fix it then.. I doubt someone will tho. 

Let's deploy this and I will test it on Production 👍  Please ping me on discord when its merged to master.

2023-06-06 11:35 UTC, Lezek123 approved these changes

2023-06-06 11:35 UTC, Lezek123 commented on src/utils/VideoRelevanceManager.ts
> +        [joystreamTimestampWeight, ytTimestampWeight],
To preserve backward-compatibility with config exported from the previous version of Orion:
```suggestion
        [joystreamTimestampWeight, ytTimestampWeight] = [7, 3],
```

2023-06-06 11:41 UTC, merged