[Nara] remove mappings for 'VideoDeletedByModerator' & 'ChannelDeletedByModerator' events
Joystream/orion pull request #193
Opened 2023-09-18 06:22 UTC by zeeshanakram3

addresses #113

2023-09-22 05:19 UTC, ignazio-bovo approved these changes
LGTM

2023-09-25 11:44 UTC, ignazio-bovo requested changes
Sorry for changing my mind but I have realized that this PR will make the `orion_db` keep all the videos/channel that have been deleted in the runtime by moderators. With the risk of Atlas query potentially fetching this when they shouldn't
I believe the issue is similar to this: https://github.com/Joystream/joystream/pull/4875#issuecomment-1725411130

The simple orion fix for this is to add an extra `phantom` parameter to the event so that types for `v12.2003` are generated for this and we can filter out those event

I believe you mentioned this already during the standup

2023-09-25 15:15 UTC, zeeshanakram3 commented
> There's no need for this PR I believe since:
> ...
> I believe you mentioned this already during the standup

Correct. The mappings won't be deleted. However, I have added a placeholder [3f14c7e](https://github.com/Joystream/orion/pull/193/commits/3f14c7ea999dbf51a2fd3ce2765d5b164cae6fb5) to mark mappings as deprecated.

2023-09-26 06:53 UTC, ignazio-bovo approved these changes

2023-09-28 11:16 UTC, merged