Adds mappings for `ChannelAssetsDeletedByModerator` & `VideoAssetsDeletedByModerator` events
Joystream/orion pull request #199
Opened 2023-10-02 06:40 UTC by zeeshanakram3

address #194

2023-10-03 13:39 UTC, ignazio-bovo requested changes
My comments basically asks to evaluate whether we should remove related `StorageDataObjects`

2023-10-03 13:39 UTC, ignazio-bovo commented on src/mappings/content/video.ts
> +  })
Could you please check whether is it suitable to also remove the related `StorageDataObject` rows starting from `assetIds`. If you go through the `processVideoDeletion` I believe data objects are not deleted but in the rutnime they are.
So maybe the same considerations apply also there

2023-10-03 13:39 UTC, ignazio-bovo commented on src/mappings/content/channel.ts
> +
Maybe also here you should deleted relevant `StorageDataObject`s.

2023-10-04 13:43 UTC, zeeshanakram3 commented
> My comments basically ask to evaluate whether we should remove related `StorageDataObjects`

Whenever the `ChannelAssetsDeletedByModerator` or `VideoAssetsDeletedByModerator` events are emitted by the runtime, the `DataObjectsDeleted` event is also emitted (this is due to the call made to Storage modules [delete_data_objects](https://github.com/Joystream/joystream/blob/a03082ebaf39e8e2006b0892c087a8b64f7abcbd/runtime-modules/content/src/lib.rs#L958) function from the extrisnsic).

So eventually the assets will be removed from Orion db in the [processDataObjectsDeletedEvent](https://github.com/zeeshanakram3/orion/blob/d9f370614559cd56b8d1cf36af770ffbf33e374b/src/mappings/storage/index.ts#L332) mapping, even before `*AssetsDeletedByModerator`  mappings are processed

2023-10-04 14:20 UTC, merged