🧮 Aggregate channel payments
Joystream/orion pull request #222
Opened 2023-11-02 13:53 UTC by thesan

2023-11-06 14:45 UTC, ignazio-bovo requested changes
Looks ok, I have just left small suggestions

2023-11-06 14:45 UTC, ignazio-bovo commented on schema/channels.graphql
> +  cumulativeRewardPaid: BigInt!
I think it is hard now to know the difference between reward claimed vs paid.
```suggestion
  cumulativeReward: BigInt!
```
From what I understand we want to track `rewardClaimed + membershipMetadataPayment` 
So I think this is a more appropriate

2023-11-06 14:45 UTC, ignazio-bovo commented on src/mappings/content/channel.ts
> +    cumulativeRewardPaid: 0n,
```suggestion
    cumulativeReward: 0n,
```

2023-11-06 14:45 UTC, ignazio-bovo commented on src/mappings/content/metadata.ts
> +  channel.cumulativeRewardPaid += amount
```suggestion
  channel.cumulativeReward += amount
```

2023-11-06 14:45 UTC, ignazio-bovo commented on schema/channels.graphql
> +  cumulativeRewardPaid: BigInt!
Alternatively you could just keep an extra `cumulativeRewardFromMembers` and then on atlas you could rank by `cumulativeRewardClaimed + cumulativeRewardFromMembers`

2023-11-06 16:46 UTC, thesan commented
@ignazio-bovo I renamed the field but I don't understand why after I (drop the db and) regenerate the migration the db field is still called `cumulative_reward_paid` :confused:

2023-11-07 10:36 UTC, ignazio-bovo commented
Also please add the migration for the `NextEntityId` in the `src/utils/offchainState`
```typescript
  private globalCountersMigration = {
    // destination version : [global counters names]
    '3.0.1': ['Account'],
    '3.0.2': ['Account'],
    '3.0.3': ['Account'],
    '3.0.4': ['Account'],
  }
    ```

2023-11-07 11:13 UTC, ignazio-bovo approved these changes
LGTM

2023-11-07 11:13 UTC, merged