Fix/homepage scoring
Joystream/orion pull request #251
Opened 2023-11-24 15:07 UTC by WRadoslaw

#245

2023-11-27 16:49 UTC, ignazio-bovo reviewed
It looks ok, it's just the update query it's a bit complex now to read
Also to make sure:
Are we removing the trigger to updating the score in favour of a higher updating frequency?

2023-11-27 16:49 UTC, ignazio-bovo commented on src/utils/VideoRelevanceManager.ts
>    }
Can you maybe break down this complex query into smaller pieces for better readability? Even with Copilot is a bit complex to decipher

2023-12-02 15:58 UTC, zeeshanakram3 requested changes
Looks good, I noticed that you removed the `scheduleRecalcForVideo` method. Although it was not used right now, I think this could have been a very useful addition if used properly. We can have two different relevance score calculation intervals, a smaller interval (e.g. 10 mins) for all the scheduled videos (i.e. scheduled due to view, comments, channel weight updates, etc.), and a larger interval for table-wide recalculation.

Since the `video` table is growing rapidly I think recalculation of the relevance score for all the videos every 10 minutes, is not ideal, so the relevance score update for the whole table can be every 12/24 hours.

2023-12-05 08:24 UTC, zeeshanakram3 requested changes
Looks good. Just a couple of points

- Please include this change to avoid potential Postgres deadlocks (https://github.com/Joystream/orion/issues/268#issuecomment-1838647280)

- What do you think about this `We can have two different relevance score calculation intervals, a smaller interval (e.g. 10 mins) for all the scheduled videos (i.e. scheduled due to view, comments, channel weight updates, etc.), and a larger interval for table-wide recalculation.` from my [comment](https://github.com/Joystream/orion/pull/251#pullrequestreview-1760917652).

2023-12-05 10:18 UTC, zeeshanakram3 requested changes

2023-12-05 10:18 UTC, zeeshanakram3 commented on src/utils/VideoRelevanceManager.ts
> +  scheduledUpdateLookTime: number
I think you meant `Loop` instead of `Look`

```suggestion
  scheduledUpdateLoopTime: number
```

2023-12-05 14:11 UTC, zeeshanakram3 approved these changes
LGTM

2023-12-05 17:00 UTC, zeeshanakram3 commented
Couple of things that I missed in the review:

- Can you please schedule the recalc in the setChannelWeights mutation too (https://github.com/wradoslaw/orion/blob/1eba2c40642ac23a66656b6a15b2bc1735c71c09/src/server-extension/resolvers/AdminResolver/index.ts#L198)
- Now full table calculation is set at 12 hrs, so effectively after each deployment till 12 hours Gleev homepage wont have the correct videos since full recalculation has not happened yet. So maybe we should run the full recalc. at the start of the new deployment and after the state import? WDYT?

Would you please address these before the tomorrow's deployment. Thanks

2023-12-05 20:30 UTC, WRadoslaw commented
> Couple of things that I missed in the review:
> 
> * Can you please schedule the recalc in the setChannelWeights mutation too (https://github.com/wradoslaw/orion/blob/1eba2c40642ac23a66656b6a15b2bc1735c71c09/src/server-extension/resolvers/AdminResolver/index.ts#L198)
> * Now full table calculation is set at 12 hrs, so effectively after each deployment till 12 hours Gleev homepage wont have the correct videos since full recalculation has not happened yet. So maybe we should run the full recalc. at the start of the new deployment and after the state import? WDYT?
> 
> Would you please address these before the tomorrow's deployment. Thanks

1. Ok.
2. It's already done [here](https://github.com/Joystream/orion/blob/1eba2c40642ac23a66656b6a15b2bc1735c71c09/src/processor.ts#L333), it doesn't show up, because this change is older than my PR

2023-12-06 09:27 UTC, merged