New CRT marketplace query
Joystream/orion pull request #336
Opened 2024-06-11 20:17 UTC by ikprk

2024-07-14 11:17 UTC, zeeshanakram3 requested changes
Please run `npm run generate:docs:auth-api` auth API docs

2024-07-14 11:17 UTC, zeeshanakram3 commented on src/server-extension/resolvers/CreatorToken/index.ts
> +    return result as TokenReturnType[]
Incorrect type? `ammVolume` is not a field in `TokenReturnType `

2024-07-14 11:17 UTC, zeeshanakram3 commented on src/server-extension/resolvers/CreatorToken/index.ts
> +`
```suggestion
    const topTokensCtes = `
      WITH tokens_volumes AS (
          SELECT
              ac.token_id,
              SUM(tr.price_paid) as ammVolume
          FROM
              amm_transaction tr
              JOIN amm_curve ac ON ac.id = tr.amm_id
          WHERE
              tr.created_in >= $ { lastProcessedBlock - args.periodDays * BLOCKS_PER_DAY }
          GROUP BY
              token_id
      )
    `
```

2024-07-15 11:07 UTC, ikprk commented on src/mappings/token/index.ts
> +    (amm.ammSlopeParameter * BigInt(token.totalSupply)) / BigInt(2) + amm.ammInitPrice
tbh I copied it over from Atlas, Ignazio knows the details of this calc

2024-07-15 11:11 UTC, ikprk commented on src/auth-server/handlers/registerUserInteraction.ts
> +          dayTimestamp: new Date(),
I think we match by day only in the resolver, but it seems like a good improvement anyway

2024-07-15 11:15 UTC, ikprk commented on src/server-extension/resolvers/StateResolver/index.ts
> +    const result: { entity_id: string; entrycount: number }[] = await em.query(`
Hmmm, it does wont correctly, so I wouldn't change it

2024-07-15 11:36 UTC, ikprk commented on src/server-extension/resolvers/StateResolver/types.ts
> +  type: string
Hmmm, good question. On one side there might be a scenario where we would like to use this logic in more that one place, maybe with new type, so each change would require Orion changes as well. Do you see any security problem here? If not, maybe we can leave it as it is, and Atlas  shall be responsible for making sure to use some common variable to reference certain `type`.

2024-07-15 11:38 UTC, ikprk commented on src/server-extension/resolvers/StateResolver/types.ts
> +  type: string
@dmtrjsg do you think we will have more logic like hot tokens on marketplace that will require us to count some channel, video or whatever entity inside Atlas to show the most clicked ones?

2024-07-15 11:56 UTC, zeeshanakram3 commented on src/server-extension/resolvers/StateResolver/index.ts
> +    const result: { entity_id: string; entrycount: number }[] = await em.query(`
you mean work?

2024-07-19 10:10 UTC, zeeshanakram3 commented on src/server-extension/resolvers/CreatorToken/index.ts
> +    listQuerySql = listQuerySql.replace(/marketplace_token/g, 'marketplace_tokens')
This should not be required any longer?

2024-07-19 13:39 UTC, merged